### ISSUE TITLE
What does rank file mean?

### ISSUE THREAD

**Issue by ghost** [sordonia/hred-qs#2]
Hi, Sordonj, Thanks for your great work.
I have some problem running the convert-text2dict.py,
I know [session file] means query serises, how about [rank_file]?

**Comment by sordonia** [comment]
Hi !

rank_file is a tab separated file (each line has the same number of fields
as the session file) with the rank of the first clicked document for each
query.
Actually, this is an idea i wanted to test out but didn't have time. you
can just set all the entries in the rank_file to 0, i.e.

if session file is:

yahoo search '\t' search engine '\t' search

then rank file is:
0 '\t' 0 '\t' 0

**Comment by ghost** [comment]
Got it! Thank you.
