### ISSUE TITLE
 'context_to_indices' is not defined in suggest.py

### ISSUE THREAD

**Issue by ghost** [sordonia/hred-qs#3]
Hi! sordonia,Thanks for your comment in the last issue.
But a NameError problem occured when running suggest.py

error message:
Traceback (most recent call last):
  File "suggest.py", line 110, in <module>
    main()
  File "suggest.py", line 102, in main
    seqs = context_to_indices(lines, model)
NameError: global name 'context_to_indices' is not defined

**Comment by sordonia** [comment]
Hi!

Sorry, you can just use sample.py. suggest.py was related to another project and should be removed. thanks for noticing

**Comment by ghost** [comment]
got it!Thanks a lot~
